spring:
  datasource:
    url: jdbc:mysql://localhost:3306/degree0?allowPublicKeyRetrieval=True&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: jsy251361
  redis:
    host: 127.0.0.1
    port: 6379
    password:

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传相关配置
file:
  # 本地上传服务配置
  local:
    # 上传文件访问路径
    access-path: /file/**
    # 上传文件保存路径，注意：最后带上反斜杠
    upload-path: /Users/chouchou/upload/boot/
    # 上传文件访问URL前缀
    access-url: http://localhost:${server.port}/api/file

# 日志配置，logback-spring.xml中会引用以下变量
logback-spring:
  # 日志文件目录
  path: logs

